name: flutter_test_guia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
